# Generated by Django 5.2.12 on 2026-04-06 03:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codes', '0001_initial'),
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='address',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='school',
            name='city',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='name',
            field=models.CharField(default=None, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='school',
            name='phone',
            field=models.CharField(default=None, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='school',
            name='phone_code',
            field=models.CharField(default=None, max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='school',
            name='school_id',
            field=models.CharField(default=None, editable=False, max_length=3, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='school',
            name='state',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='codes.state', to_field='code_value'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='school',
            name='zip_code',
            field=models.CharField(default=None, max_length=5),
            preserve_default=False,
        ),
    ]
