# Generated by Django 5.2.12 on 2026-04-05 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_people_ssn'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='phone_code',
            field=models.CharField(default=None, max_length=4),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='people',
            name='address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='people',
            name='city',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='people',
            name='middle_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='people',
            name='ssn',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='people',
            name='state',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='people',
            name='zip_code',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
