# Generated by Django 5.2.12 on 2026-04-06 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_alter_maritalstatus_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_value', models.CharField(max_length=3, unique=True)),
                ('name', models.CharField(max_length=15)),
                ('long_name', models.CharField(max_length=30)),
            ],
        ),
    ]
