# Generated by Django 5.2.12 on 2026-04-06 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0005_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='state',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
