# Generated by Django 5.2.12 on 2026-04-06 02:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codes', '0001_initial'),
        ('people', '0006_alter_people_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='gender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='codes.gender', to_field='code_value'),
        ),
        migrations.AlterField(
            model_name='people',
            name='marital_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='codes.maritalstatus', to_field='code_value'),
        ),
        migrations.AlterField(
            model_name='people',
            name='nationality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='codes.nationality', to_field='code_value'),
        ),
        migrations.AlterField(
            model_name='people',
            name='person_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='codes.persontype', to_field='code_value'),
        ),
        migrations.DeleteModel(
            name='State',
        ),
        migrations.AlterField(
            model_name='people',
            name='state',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='codes.state', to_field='code_value'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Gender',
        ),
        migrations.DeleteModel(
            name='MaritalStatus',
        ),
        migrations.DeleteModel(
            name='Nationality',
        ),
        migrations.DeleteModel(
            name='PersonType',
        ),
    ]
