# Generated by Django 5.2.12 on 2026-04-06 03:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0007_alter_people_gender_alter_people_marital_status_and_more'),
        ('school', '0002_school_address_school_city_school_name_school_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='school',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='school.school'),
            preserve_default=False,
        ),
    ]
